### ISSUE TITLE
msgfmt segfaults building weechat 1.9.1

### ISSUE THREAD

**Issue by rofl0r** [sabotage-linux/gettext-tiny#14]
```
/bin/msgfmt -o /src/build/weechat/weechat-1.9.1/build/po/cs.gmo /src/build/weechat/weechat-1.9.1/build/po/cs.po
Segmentation fault
```

**Comment by rofl0r** [comment]
it segfaults during qsort.
breaking before that reveals:
```
Breakpoint 2, process (in=0x62b520, out=0x62b020) at src/msgfmt.c:453
453             qsort(d.strlist, d.num[pe_msgid], sizeof (struct strmap), strmap_comp);
(gdb) p/x d.num
$9 = {0xffffffff, 0x0, 0x0, 0xffffffff}
```
d.num[pe_msgid] is -1.
i guess it happened here:

```c
static inline void writestr(struct callbackdata *d, struct po_info *info) {
...
                d->num[pe_msgid]--;
                d->num[pe_msgstr]--;
```

**Comment by xhebox** [comment]
@rofl0r 
I have commited fix codes locally. As discussed on irc: writestr() has a logical hole, fixed already.

And 2:
```
cd /home/xhe/project/weechat/build/po && /bin/msgmerge --quiet --update --backup=none /home/xhe/project/weechat/po/cs.po /home/xhe/project/weechat/build/po/weechat.pot
```

Due to the unworking function, msgmerge gave that empty file. As our goal is not to provide these utils of translators, i think we should make a dump --update which exactly outputs the original .po files.

**Comment by rofl0r** [comment]
> Due to the unworking function, msgmerge gave that empty file. As our goal is not to provide these utils of translators, i think we should make a dump --update which exactly outputs the original .po files.

sounds good

> I have commited fix codes locally.

why not push them to a branch ?

**Comment by rofl0r** [comment]
i left some notes for you in the chatroom

**Comment by rofl0r** [comment]
merged as https://github.com/sabotage-linux/gettext-tiny/commit/57f10174a0c15f63d949ec154c5ffff71a09c75e

**Comment by ismaell** [comment]
I'm seeing a build failure (abort) with Weechat 2.4 and 2.5; maybe unrelated as the `.po` file isn't empty. I'll try to provide a backtrace later.

**Comment by xhebox** [comment]
@ismaell Confirmed. GNU msgfmt will also trigger an error for empty po file. Tiny matched GNU in this aspect. But i saw with GNU msgfmt, it did not even try to build the empty po file. I'll look into it more precisely, please open another issue.
