### ISSUE TITLE
reported error building "attr-git"

### ISSUE THREAD

**Issue by rofl0r** [sabotage-linux/gettext-tiny#15]
@selkfoster from dragora linux reports errors with latest git building "attr-git" (i suppose that means package attr using latest git checkout) : http://sprunge.us/dXYD

i can see several issues there:

1) `msgmerge --update  --lang=es es.po attr.pot` seems to write to stdout, which seems to be unexpected

2) `/bin/sh: msgconv: not found` - it is not clear from where `msgconv` is called and what it's supposed to do and if we should ship it

**Comment by xhebox** [comment]
@rofl0r 
1. confirmed
2. i should have clean all such codes, though there's a lack in handling `en@boldquot` like name, i doubt if they are using autopoint from GNU, need more infomation
```
sed -e '/^#/d' -e 's/HEADER/en@boldquot.header/g' ./insert-header.sin > en@boldquot.insert-header
```

**Comment by rofl0r** [comment]
> did not see msgmerge, neither msgconv or the command above

you mean you didn't see it when you tried to reproduce, or in the log in the pastebin ?

**Comment by xhebox** [comment]
@rofl0r i did not see, i have used 'grep -r -H MSGFMT' or 'MSGCONV'

**Comment by rofl0r** [comment]
@xhebox do you have time to look at these issues ? i think it's important that we fix them quickly, since it appears some other distros are looking into adopting gettext-tiny, which is important for the musl community - and if we wait too long they may lose interest and stick with the bloated GNU gettext...

**Comment by xhebox** [comment]
@rofl0r sorry, i am really busy with studies, and since sth you know, that firewall of our land, i am trying to write a stable proxy tool these days... I have looked into these issues, just did not code, now i have pushed 2 new commits. issue 16 is safe to close, and this issue, we need more feedbacks, i doubt they are using Makefile.in from GNU, so msgconv is invoking, this is unexpected

**Comment by xhebox** [comment]
@rofl0r  any update? it seem all OK there. i built it again. And for `boldquot`, it seems that they will remove those invalid files when they release:
```
[root@xhe-PC po]# cat .gitignore 
*.gmo
*.sed
*.sin
attr.pot
Makefile.in.in
Makevars.template
POTFILES
POTFILES.in
Rules-quot
en@boldquot.*
en@quot.*
stamp-po
```

**Comment by rofl0r** [comment]
i have no idea. you say the issues have disappeared ? then i guess this can be closed.

**Comment by xhebox** [comment]
yeah, the last problem is the one i said in https://github.com/sabotage-linux/gettext-tiny/issues/15#issuecomment-339028788. And i found that actually they wont release those files in tarballs... So if it's downloading rather than `git clone`, the problem i met will disappear.

**Comment by rofl0r** [comment]
ok, thanks. then i guess i'll just close it.
