### ISSUE TITLE
config.rpath missing when AC_CONFIG_AUX_DIR is set

### ISSUE THREAD

**Issue by mako2580** [sabotage-linux/gettext-tiny#18]
Hi,
I discovered that config.rpath is missing when AC_CONFIG_AUX_DIR is set in configure.ac. And that's because you touch config.rpath in autopoint but you are not checking AC_CONFIG_AUX_DIR destination. That is 'build-aux' for example in acl and attr package. I also created dirty fix patch for it.
[auxdir.patch.txt](https://github.com/sabotage-linux/gettext-tiny/files/1786729/auxdir.patch.txt)

**Comment by rofl0r** [comment]
thanks!
i'm posting your patch here inline for discussion and with the typo fixed:
```diff
--- a/src/autopoint.in
+++ b/src/autopoint.in
@@ -6,7 +6,16 @@
 	cp -f $i m4/
 done
 
-touch config.rpath ABOUT-NLS
+grep -q "AC_CONFIG_AUX_DIR" configure.ac
+
+if [ $? -eq 0 ] ; then
+  dirprefix=$(grep "AC_CONFIG_AUX_DIR" configure.ac | cut -d '[' -f 2 | cut -d ']' -f 1)"/"
+  mkdir -p ${dirprefix}
+else
+  dirprefix=""
+fi
+
+touch ${dirprefix}config.rpath ${dirprefix}ABOUT-NLS
 
 for i in intl/Makefile.in po/Makefile.in.in ; do
 	install -D -m 644 @datadir@/data/autopoint_Makefile.in "$i"
```

**Comment by xhebox** [comment]
Good catch! Patch is OK, but i think we could simply do like the following:
```
dirprefix=$(grep "AC_CONFIG_AUX_DIR" configure.ac | cut -d '[' -f 2 | cut -d ']' -f 1)"/"
if [ "$dirprefix" ] ; then
    mkdir -p ${dirprefix}
fi
```

**Comment by mako2580** [comment]
Wouldn't first xhebox's code suffer from unwanted behavior, when there will be no AC_CONFIG_AUX_DIR in configure.ac and grep will return nothing and so cut too and then you add "/" ? Then you will do `touch /config.rpath` which is not what you wanted. And the second one, on the other hand will be missing "/". But it could be solved by `touch ./${dirprefix}/config.rpath`

**Comment by xhebox** [comment]
@mako2580 Yeah, they will touch files at the wrong position, thanks for your reminding :). By the way, are you willing to make a pull request? So your github account will appear in the commit. Not to force you, i will make a commit if you are too lazy to do it.

@rofl0r It looks good enough to me, what do you think?

**Comment by mako2580** [comment]
OK, I will make pull request

**Comment by xhebox** [comment]
Nice! Then let's wait for rofl0r.

**Comment by xhebox** [comment]
@mako2580 https://github.com/sabotage-linux/gettext-tiny/commit/8ed33e336a8eb96e0990aa52e7e374a163b75dbd, close the issue if it works :)

**Comment by mako2580** [comment]
As it turns out, when I was trying to compile `bison` package it was complaining that `ABOUT-NLS` is missing and `AC_CONFIG_AUX_DIR` was set to `build-aux` so it looks like `ABOUT-NLS` shouldn't have `./${dirprefix}`. I will try to fix it tomorrow, because it looks it needs more fixes to successfully compile. Because I edited `autopoint` locally, but still there were some errors.

**Comment by xhebox** [comment]
@rofl0r @mako2580 Any issue left? If no, let's close it again.
