### ISSUE TITLE
Dynamically copy Makefile.in.in

### ISSUE THREAD

**Issue by mako2580** [sabotage-linux/gettext-tiny#21]
I was trying to compile `pacman` package, and it has multiple location of `po` files. It was complaining about missing `lib/libalpm/po/Makefile.in.in`. But you're only copying it to `po/Makefile.in.in` so I tried to create fix. It's first version so I'm open to ideas.

```diff
--- a/src/autopoint.in
+++ b/src/autopoint.in
@@ -18,8 +18,8 @@
 
 touch ./${dirprefix}/config.rpath ABOUT-NLS
 
-for i in intl/Makefile.in po/Makefile.in.in ; do
-	install -D -m 644 @datadir@/data/autopoint_Makefile.in "$i"
+for polocation in $(find -name POTFILES.in) ; do
+	install -D -m 644 @datadir@/data/autopoint_Makefile.in ./${polocation%/POTFILES.in}/Makefile.in.in
 done
 
 install -D -m 644 @datadir@/data/Makevars.template po/Makevars.template

```

As you can see above I disabled copying `autopoint_Makefile.in` to `intl/Makefile.in` and tried to compile some of packages that need `gettext` and everything worked. So I would like to ask why was `intl/Makefile.in` there ?

**Comment by rofl0r** [comment]
according to the comment of the git commit that added autopoint, it was developed using a git checkout of weechat and glib, so that might the origin... other than that i don't really recall any details. i will try now to gather information about POTFILES.in, i hope that it can only exist in a limited number of hardcoded places so we dont have to use `find`, which could become really slow.

**Comment by mako2580** [comment]
I found another option instead of `find`. It is list of directories which contain `po/Makefile.in` in `configure.ac`. 

And it can be achieved by this patch :

```
--- a/src/autopoint.in
+++ b/src/autopoint.in
@@ -14,6 +14,12 @@
     dirprefix=${dirprefix%%])*}
     mkdir -p ${dirprefix}
   fi
+  
+  if [ "${line##*po/Makefile.in}" != "$line" ]; then
+    poprefix=${line//[[:space:]]}
+    poprefix=${poprefix%%po/Makefile.in*}
+    install -D -m 644 @datadir@/data/autopoint_Makefile.in ./${poprefix}/po/Makefile.in.in
+  fi
 done < "configure.ac"
 
 touch ./${dirprefix}/config.rpath ABOUT-NLS
```

**Comment by rofl0r** [comment]
can you explain what it does ? i'm not really familiar with those substitution expressions (also, are they POSIX sh compatible, or bashisms?)

**Comment by mako2580** [comment]
OK so it's mainly copy-paste of what @xhebox created on fixing https://github.com/sabotage-linux/gettext-tiny/issues/18 issue. It should be pure posix shell, as he written. It is inside `for` cycle parsing `configure.ac`. And when line containing `po/Makefile.in` occurs, then it erase spaces from beginning (if there are any). Then erase `po/Makefile.in` and everything until end of line. And from that we get variable `poprefix`, which we use as a destination for `po/Makefile.in.in`. And that's all.

**Comment by rofl0r** [comment]
interesting.
could you elaborate in detail how this line works ? `if [ "${line##*po/Makefile.in}" != "$line" ]; then`

what does the expression `${line##*po/Makefile.in}` produce ?

since we're parsing configure.ac, i would expected that `lib/libalpm` uses its own configure.ac. it's interesting that it is referenced in the top level configure.ac.

**Comment by mako2580** [comment]
`##` in shell strips the longest match from front of string, and we check if string hasn't changed. Because if `"${line##*po/Makefile.in}" != "$line"`, it means that in the line there was `po/Makefile.in`. And because we have `*` in front of `po/Makefile.in` so it will erase everything until `po/Makefile.in`. That means that expresion `${line##*po/Makefile.in}` should produce empty string. But that whole `if` condition is only replacement of `grep "po/Makefile.in"`

**Comment by rofl0r** [comment]
ok. i tested this 
```
line="foo bar baz po/Makefile.in bla"
printf "%s" "${line##*po/Makefile.in}"
```
and the `##* ` stuff is essentially `printf "%s" "$line" | sed 's,^.*po/Makefile.in,,'` so when that doesn't equal the original line it tells us that the string was contained in line... not exactly very readable... but oh well, at least it's faster than calling sed or grep for each line (i don't see usage of grep or sed or cut as a problem, because if you lack any of them, you have *huge* trouble...)

**Comment by rofl0r** [comment]
so from my side this looks OK to merge. could you prepare a PR please ?

**Comment by xhebox** [comment]
@mako2580 @rofl0r 
As for the usage of grep/sed, yeah, it's not a big deal. But i have met cases where i need to build grep but i lacked grep to pass configuration for about 4~5 times, tough it's not autopoint. Bad things always happen, That's what i thought.

The idea is nice, but i have to point out some problem:

1. `${line//[[:space:]]}` is bashism, regex is not, but the substitution. 

http://pubs.opengroup.org/onlinepubs/009695399/utilities/xcu_chap02.html#tag_02_06_02

I will try to do something like `${v## }$`

2. We can never know if it looks like ` ...po/...` or `AC_CONFIG_FILES(...po...`. This is weird, but possible.

3. Most release tarballs do not contain configure.ac at all, it needs the original value as a fallback option.

4. For path containing `space` or else, it needs double quote. We missed them not only in this patch but also the previous pr.

**Comment by rofl0r** [comment]
> 3. Most release tarballs do not contain configure.ac at all, it needs the original value as a fallback option.

unless i'm missing something, autopoint is only needed for `autoreconf -i`, that means it is always used with configure.ac, and never with pregenerated configure script.

**Comment by xhebox** [comment]
Ah, indeed. Then, there're three problems left.

**Comment by mako2580** [comment]
OK, so this block of code should solve first and second problem
```
if [ "${line##*po/Makefile.in}" != "$line" ]; then
    poprefix=${line##*[}
    poprefix=${poprefix%%po/Makefile.in*}
    install -D -m 644 @datadir@/data/autopoint_Makefile.in "./${poprefix}/po/Makefile.in.in"
fi
```

It was tested on `configure.ac` containing :

```
# Configuration files
AC_CONFIG_FILES([
lib/libalpm/Makefile
     [lib/libalpm/po/Makefile.in
lib/libalpm/libalpm.pc
src/common/Makefile
src/pacman/Makefile
  ([src/pacman/po/Makefile.in
src/util/Makefile
scripts/Makefile
 AC_CONFIG_FILES([scripts/po/Makefile.in
doc/Makefile
etc/Makefile
test/pacman/Makefile
test/pacman/tests/Makefile
test/scripts/Makefile
test/util/Makefile
Makefile
])
```

and it parsed this

```
lib/libalpm/
src/pacman/
scripts/
```

So I guess it's working

**Comment by mako2580** [comment]
I forgot to add previous testing with

```
# Configuration files
AC_CONFIG_FILES([
lib/libalpm/Makefile
     lib/libalpm/po/Makefile.in
lib/libalpm/libalpm.pc
src/common/Makefile
src/pacman/Makefile
  src/pacman/po/Makefile.in
src/util/Makefile
scripts/Makefile
 AC_CONFIG_FILES([scripts/po/Makefile.in
doc/Makefile
etc/Makefile
test/pacman/Makefile
test/pacman/tests/Makefile
test/scripts/Makefile
test/util/Makefile
Makefile
])
```

And it also parsed succesfully

```
lib/libalpm/
src/pacman/
scripts/
```

**Comment by xhebox** [comment]
Could you post your test scripts? I guess you are using echo, right? And without `"$v"`, if `$v`, the space will simply disappear, because it's not seen as a part of variable value, but whitespaces between the `=` and the `value`.

And this will fail when we added `""` to solve the fourth problems, or write sth like `./...$v`(that will be treated as two arguments).

**Comment by mako2580** [comment]
My test script contains this

```
if [ "${line##*po/Makefile.in}" != "$line" ]; then
    poprefix=${line##*[}
    poprefix=${poprefix%%po/Makefile.in*}
    echo -n A
    echo -n "$poprefix"
    echo B
    install -D -m 644 /usr/share/gettext-tiny/data/autopoint_Makefile.in "./${poprefix}/po/Makefile.in.in"
fi
```

And output is

```
Alib/libalpm/B
Asrc/pacman/B
Ascripts/B
```

**Comment by xhebox** [comment]
Ah, i got it. `while read line` acts same as normal assignment expressions, so that's exactly like what i said. The spaces were already removed before all of your actions.

http://pubs.opengroup.org/onlinepubs/009695399/utilities/read.html

And then, just left one problem.

**Comment by mako2580** [comment]
If you have `""` on mind, I have added them on this block of code and I will do it also for the previous code we merged previously. So I think there's no problem left.

**Comment by xhebox** [comment]
No, still need pr :). If it's at your convenience, i'd like to see two commits, one for dynamically copy, another for `""`.

**Comment by xhebox** [comment]
@mako2580 I rebased the repo. Some more comments. Btw, i removed some trailing whitespaces in the first commit, `AC..` commit(found it by accident).
