### ISSUE TITLE
gl_TYPE_WINT_T_PREREQ is missing

### ISSUE THREAD

**Issue by mako2580** [sabotage-linux/gettext-tiny#23]
Hi,
During building `nano` package I discovered, that `gl_TYPE_WINT_T_PREREQ` is missing, and therefore I'm unable to compile it. So I looked to `gettext` and copied block of code from it and it worked. Patch would look like this

```diff
--- a/m4/wint_t.m4
+++ b/m4/wint_t.m4
@@ -60,3 +60,15 @@
   fi
   AC_SUBST([GNULIB_OVERRIDES_WINT_T])
 ])
+
+dnl Prerequisites of the 'wint_t' override.
+AC_DEFUN([gl_TYPE_WINT_T_PREREQ],
+[
+  AC_CHECK_HEADERS_ONCE([crtdefs.h])
+  if test $ac_cv_header_crtdefs_h = yes; then
+    HAVE_CRTDEFS_H=1
+  else
+    HAVE_CRTDEFS_H=0
+  fi
+  AC_SUBST([HAVE_CRTDEFS_H])
+])
```

**Comment by rofl0r** [comment]
ok, PR pls :)

**Comment by rofl0r** [comment]
i wonder how that one got missed. i recently updated the m4 stuff from gnulib git...

**Comment by xhebox** [comment]
@rofl0r  could we close the issue? did you find anything new?
