### ISSUE TITLE
autopoint does not create `install` target, nor generate actual .mo build instructions

### ISSUE THREAD

**Issue by awilfox** [sabotage-linux/gettext-tiny#25]
Generating procps' build system (`./autogen.sh`) with gettext-tiny's `autopoint` has left the build system unable to `make install`:

```
Making install in po
make[2]: Entering directory '/usr/src/packages/system/procps/src/procps-v3.3.15-7bb949bcba13c107fa0f45d2d0298b1ad6b6d6cc/po'
make[2]: *** No rule to make target 'install'.  Stop.
make[2]: Leaving directory '/usr/src/packages/system/procps/src/procps-v3.3.15-7bb949bcba13c107fa0f45d2d0298b1ad6b6d6cc/po'
make[1]: *** [Makefile:1841: install-recursive] Error 1
```

It seems to have generated three files in the `po` directory: `Makefile`, `Makefile.in`, and `Makefile.in.in`, all containing just:

```make
all:
clean:
dist:
distclean:
.PHONY: all clean dist distclean
```

This also broke `make check-recursive`.

**Comment by xhebox** [comment]
@awilfox i did not met this problem, could you post your instructions?
@rofl0r But i do met another problem...: 
```
./autogen.sh: 64: ./autogen.sh: po/update-potfiles: not found
```

**Comment by awilfox** [comment]
I downloaded the [3.3.15 release](https://gitlab.com/procps-ng/procps/repository/archive.tar.gz?ref=v3.3.15), and ran: `./autogen.sh`.

This is using gettext-tiny 0.2.0 release, not git master.  It didn't look like anything had changed in autopoint between then.

Adding blank `clean` and `install` targets to `/usr/bin/autopoint` fixed the build error, but it didn't actually create any .mo files, so that isn't going to help (no translations are built nor installed).  Is there a reason the GNU gettext Makefile.in.in isn't shipped with gettext-tiny?  [That file is public domain](http://www.sympa.org/distribution/sympa-6.1.25/po-wwsympa/Makefile.in.in), not GPL, so it should be redistributable with gettext-tiny.

**Comment by rofl0r** [comment]
> Is there a reason the GNU gettext Makefile.in.in isn't shipped

yeah, the reason is i originally intended gettext-tiny to be a just-stubs implementation, but thanks to the work of @xhebox it evolved into a fully conforming implementation.

that said, if you think that copying that template from GNU instead of ours would fix it, could you please make a PR, @awilfox ?

**Comment by xhebox** [comment]
@rofl0r missing `update-potfiles`may be a mistake by procps guys or sourceforge...  It's ok to use the one from awilfox. If awilfox got all these working, let's release a new version.. :)

**Comment by rofl0r** [comment]
yeah, i wanted to wait for feedback from @awilfox

**Comment by awilfox** [comment]
The abort trap was actually useful in finding a [bug in procps](https://gitlab.com/procps-ng/procps/merge_requests/68), but thanks for implementing the BEL character anyway :)

I will try the latest git master and see if that fixes it.  One problem with shipping the "real" Makefile.in.in is that the `GETTEXT_MACRO_VERSION` has to exactly match the M4 stuff, so it would have to be kept in sync.  Specifically, since m4/po.m4 has `AC_SUBST([GETTEXT_MACRO_VERSION], [0.19])`, we would need to ship 0.19 Makefile.in.in.

**Comment by awilfox** [comment]
Pulled git master and packaged it up at "0.3.0-pre1", pushed that to the builder and then rebuilt procps.  Worked flawlessly.  Looks great, thanks!

**Comment by rofl0r** [comment]
great, thanks for confirming! closing.
