### ISSUE TITLE
`msgmerge --version` confuses CMake

### ISSUE THREAD

**Issue by awilfox** [sabotage-linux/gettext-tiny#26]
[CMake expects `msgmerge --version` to match the following regular expression](https://gitlab.kitware.com/cmake/cmake/blob/v3.11.4/Modules/FindGettext.cmake#L64):

```
^msgmerge \(.*\) ([^0-9.]+)
```

As it stands, that is not the case.  This causes CMake to fail its own test suite (`GETTEXT_VERSION_STRING` is not defined despite `GETTEXT_FOUND`); if that test failure is ignored, it still won't set `GETTEXT_VERSION_STRING` correctly, which some packages use.

I've written a very silly patch (that I will happily submit as a PR, if that would be easier for you) that fixes this:

```patch
--- gettext-tiny-0.3.0_pre1/src/msgmerge.c.old  2018-06-20 23:47:19.927932643 -0500
+++ gettext-tiny-0.3.0_pre1/src/msgmerge.c      2018-06-20 23:55:12.997464272 -0500
@@ -18,7 +18,7 @@
 __attribute__((noreturn))
 static void version(void) {
        fprintf(stdout,
-               "these are not (GNU gettext-tools) 99.9999.9999\n");
+               "msgmerge (GNU gettext-tools; compatible) 0.19 (gettext-tiny) 0.3.0\n");
        exit(0);
 }
 
```

However, I'm not sure if any other package looks for the exact string "(GNU gettext-tools)"... so I'm not sure if this is mergable as-is.

Further direction would be welcome and I'll be happy to build and test against whatever changes necessary.  If you would like to test yourself, from a built CMake tree run:

```
bin/ctest -R CMakeOnly.AllFindModules
```

**Comment by xhebox** [comment]
Nice! Though, msgmerge now has been a working stub despite unknown bugs, yet it is still not a full GNU like implementation. So, i do not think we should write `GNU gettext-tools; compatible` there. Maybe `gettext-tiny, not GNU gettext-tools` or so.

If you have not found any package need GNU implementation exactly, i think we better stand still to prevent it from using some GNU features. But i am happy to write codes to be compatible with GNU implementation if there's a need.

**Comment by rofl0r** [comment]
we added the 9999 version to trick stuff based on autotools.

```
xgversion="`$XGETTEXT --version|grep '(GNU ' 2> /dev/null`"
mmversion="`$MSGMERGE --version|grep '(GNU ' 2> /dev/null`"
mfversion="`$MSGFMT --version|grep '(GNU ' 2> /dev/null`"
if test -z "$xgversion" -o -z "$mmversion" -o -z "$mfversion"; then
    as_fn_error $? "GNU gettext tools not found; required for intltool" "$LINEN$
fi
```

this version comes from intltool m4 https://github.com/gabrielfalcao/guake/blob/master/m4/intltool.m4#L106 but iirc there are other similar checks that check for a specific GNU gettext version, even though i can't find any right now.

so i'd suggest we do:
msgmerge (GNU gettext-tools compatible) 99.9999.9999
without going into details about what we specifically are and which version

also we should do a full distro test build with such a change before merging it.

**Comment by rofl0r** [comment]
great, thanks for your effort!

**Comment by xhebox** [comment]
Nice!

**Comment by rofl0r** [comment]
any updates, @awilfox ?

**Comment by awilfox** [comment]
So far so good.

I've still not finished, as I had to set up new hardware (our Talos II arrived!), but every package I've built so far with that version string has built successfully and properly.  I will keep you updated and let you know if anything goes wrong, OR when I finish building everything.

The goal is to have beta1 composed by Sunday, so hopefully I will report in then.

**Comment by awilfox** [comment]
```
awilcox on gwyn /usr/src/packages/user $ msgmerge --version
msgmerge (GNU gettext-tools compatible) 99.9999.9999
```

This was used to compose the entirety of our distribution, on five CPU architectures (ppc32, ppc64, x86_64, x86, and arm64).  Besides the issues I reported here, no problems were found.

**Comment by rofl0r** [comment]
great! could you open a PR with the change? much appreciated

**Comment by rofl0r** [comment]
ping @awilfox
