### ISSUE TITLE
support for mingw/platforms with separate libiconv

### ISSUE THREAD

**Issue by rofl0r** [sabotage-linux/gettext-tiny#33]
from #31 / #32

@xhebox [suggests to use pkg-config to check for libiconv](https://github.com/sabotage-linux/gettext-tiny/issues/31#issuecomment-405033711)

> LDFLAGS=$(pkg-config --silence-errors --libs iconv)

> Tested both under win+msys2+pkg-config and linux(musl&glibc in schroot)+pkgconf. When we need iconv, there will be a flag; when there's no iconv(musl), it wont print errors so that there're no redundant strings in LDFLAGS.

> And maybe we could set a new variable PKG_CONFIG to let users choose their own pkgconf command. And maybe do not try to be smart if users said there's no pkgconf(PKG_CONFIG==NULL)?

i'm not certain. does mingw ship pkg-config support files for libiconv ? that sounds odd.
i'm also hesitant to pull in a dependcy on a new build tool requirement and associated maintenance work.

imo the "cleanest" solution would be to have a separate "configure" check:
`checking whether we need -liconv for iconv_open()... no`
but well... we don't use autoconf and writing such checks for Makefiles is tricky.

now that LDFLAGS is in the right position, we could just write into README:
`if you use mingw, use make LDFLAGS=-liconv`.

**Comment by xhebox** [comment]
I find this: https://github.com/OISF/libhtp/blob/0.5.x/m4/iconv.m4. According to it:

> dnl Some systems have iconv in libc, some have it in libiconv (OSF/1 and
> dnl those with the standalone portable GNU libiconv installed).

OSF/1 seems have been dead. And, here's a table:

seperated | bsd mingw(cygwin) uclibc klibc
--- | ---
internal | glibc musl dietlibc newlib

All libc with a seperated libiconv seems install the standalone GNU libiconv implementation. So they come with a pkg-config file naturally.

I actually also thought about if we should taking a new build tool. And, now my idea on "smart detection" is using shell built-in command `command -v pkg-config`. It output nothing when the program is not present:

```
xhe@xhe-PC MINGW64 ~
$ command -v pkg-config
/mingw64/bin/pkg-config

xhe@xhe-PC MINGW64 ~
$ command -v pkg-confg

```

Assign the output to a variable, and test. If we have `pkg-config`, we try `LDFLAGS=$(pkg-config --silence-errors --libs iconv)`. How does it sound like?

Then the only problem would be if `command` is widely supported. My finding is a [article on IBM](https://www.ibm.com/support/knowledgecenter/en/ssw_aix_71/com.ibm.aix.osdevice/korn_shell_reg_builtin_cmd_desc.html).

If this is not acceptable, let's just write some tips in README. :)

**Comment by xhebox** [comment]
@rofl0r eh, any comment?

**Comment by rofl0r** [comment]
@xhebox please see my PR. i think that should solve it neatly.

**Comment by xhebox** [comment]
@rofl0r Great! And what about the `mingw` branch?

**Comment by rofl0r** [comment]
@xhebox it can be removed, or ignored... ;)
