### ISSUE TITLE
newpoparser: issue with vim-8.1.0327

### ISSUE THREAD

**Issue by selkfoster** [sabotage-linux/gettext-tiny#40]
I am testing the new po parser for all the packages in Dragora (dragora.org).  There is a build issue while trying to compile vim, here is the relevant part of the build log:

cd xxd; CC="gcc" CFLAGS=" -g0 -Os -mtune=generic -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1" LDFLAGS="-Wl,-E -Wl,-rpath,/usr/lib64/perl5/CORE  -s -L/usr/local/lib -Wl,--as-needed" \
	make -f Makefile
make[2]: Entering directory '/usr/src/qi/build/vim-8.1.0327/src/xxd'
gcc  -g0 -Os -mtune=generic -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -Wl,-E -Wl,-rpath,/usr/lib64/perl5/CORE  -s -L/usr/local/lib -Wl,--as-needed -DUNIX -o xxd xxd.c
make[2]: Leaving directory '/usr/src/qi/build/vim-8.1.0327/src/xxd'
make[2]: Entering directory '/usr/src/qi/build/vim-8.1.0327/src/po'
OLD_PO_FILE_INPUT=yes msgfmt -v -o af.mo af.po
OLD_PO_FILE_INPUT=yes msgfmt -v -o ca.mo ca.po
Segmentation fault 
make[2]: *** [Makefile:29: ca.mo] Error 139
make[2]: Leaving directory '/usr/src/qi/build/vim-8.1.0327/src/po'
make[1]: *** [Makefile:1971: languages] Error 2

**Comment by xhebox** [comment]
@selkfoster i can not reproduce. make sure you have the latest version. i may pushed some new commits while you're not there. especially the latest one, which fixed an invalid memory access bug.

**Comment by xhebox** [comment]
@selkfoster hi, pushed some new commits, now should be OK. the main cause is due to https://github.com/sabotage-linux/gettext-tiny/commit/5539eff5d507c619735156fa9e44e0bcf1436695.

**Comment by rofl0r** [comment]
hi @selkfoster ! have you been able to test @xhebox' bugfix ?

**Comment by selkfoster** [comment]
hi @rofl0r and @xhebox Sorry, I have been busy.  I am going to test the latest commit in a moment against all the packages in Dragora.  Thanks.

**Comment by selkfoster** [comment]
I am getting  the same error about vim .  I've cloned the newpoparser commit 756bbd1. @xhebox Have you tried against this version of vim?.

**Comment by xhebox** [comment]
@selkfoster fixed. but there's another issue, @rofl0r : 
```
[xhe@PC gettext-tiny]$ LANG=C msgfmt -c ko.UTF-8.po 
ko.UTF-8.po:6: nplurals = 1...
ko.UTF-8.po:2055: ...but some messages have 2 plural forms
msgfmt: found 1 fatal error
[xhe@PC gettext-tiny]$ LANG=C msgfmt ko.UTF-8.po 
```
msgfmt let this fatal error go without a check argument, what do we do? i've met this error at glib & vim many times. in most of the implementation, i think, the useless plural form will not cause any bugs but be a gap(not musl&glibc, at least).

**Comment by rofl0r** [comment]
sorry, i don't understand. could we discuss it on IRC ?

**Comment by xhebox** [comment]
@selkfoster sorry, it's after all a beta version. vim8.1.0570 passed, you could continue to test.

**Comment by selkfoster** [comment]
Ok. I will try with the recent commit.

**Comment by selkfoster** [comment]
@xhebox It worked fine with this version of vim (vim-8.1.0327) this time!.  Now it raises another problem from git-2.19.2:

: no custom templates yet
make[1]: Leaving directory '/usr/src/qi/build/git-2.19.2/templates'
mkdir -p po/build/locale/zh_CN/LC_MESSAGES/ && msgfmt --check --statistics -o po/build/locale/zh_CN/LC_MESSAGES/git.mo po/zh_CN.po
make: *** [Makefile:2467: po/build/locale/zh_CN/LC_MESSAGES/git.mo] Error 252

**Comment by xhebox** [comment]
@selkfoster git2.20 passed :).

**Comment by rofl0r** [comment]
> @selkfoster git2.20 passed :).

does it mean git 2.19.2 works too, now ?

**Comment by rofl0r** [comment]
@xhebox if you have time could you stop by the chat so we can discuss merging of the newpoparser branch into master? thanks!

**Comment by selkfoster** [comment]
Hi guys, sorry for the long delay.  I've tested the latest gettext-tiny from the commit ece94b7 against all the packages in Dragora, a total of 463 packages.  All worked fine! the only thing is an issue with the `autopoint' script, I have a set of patches for GNU make.  Autopoint is invoked from the autoreconf, my suspect is that the parser in the autopoint script isn't passing the variable/value correctly, I need to make a further check.  Anyway, good job with the new parser!

**Comment by rofl0r** [comment]
great! could you please open a new issue for the autopoint bug and provide more details? thanks!

**Comment by xhebox** [comment]
late reply... seems #39 and #40 could be closed.

and yeah, @selkfoster, if there's an problem, could you open another issue?
