### ISSUE TITLE
Unsupported distdir target

### ISSUE THREAD

**Issue by ismaell** [sabotage-linux/gettext-tiny#43]
The bundled `Makefile`, installed by `autopoint`, does not support the `distdir` target. This makes the resulting buildsystem incapable of generating a release.

**Comment by xhebox** [comment]
i've tested with weechat. feel free to reopen if there's any bug. have a nice day.

**Comment by ismaell** [comment]
It isn't related to the weechat issues; it's a completely different matter.

**Comment by ismaell** [comment]
Thanks for the fix; I've updated the description for future references.

@rofl0r will there be a release anytime soon?

**Comment by rofl0r** [comment]
i guess one could consider making one, since there have been 44 commits since the last.
though it can't hurt if you continue testing with master for a little longer.
