### ISSUE TITLE
Missing maintainer targets in Makefile.in.in

### ISSUE THREAD

**Issue by ismaell** [sabotage-linux/gettext-tiny#44]
Missing targets:
* `update-po`
* `update-gmo`
* `maintainer-clean`
* `Makefile` -- to recreate the Makefile

**Comment by rofl0r** [comment]
PRs welcome

**Comment by xhebox** [comment]
@ismaell Fix pushed, tested. I must clarify one thing: most targets you requested are for maintainers. And it's not the goal of tiny to provide utils for maintainers. So except update-mo/gmo, other targets are just stubs.

Close the issue if you think there's no more problems.
