### ISSUE TITLE
__stack_chk_fail_local on gettext-tiny (master/x86)

### ISSUE THREAD

**Issue by selkfoster** [sabotage-linux/gettext-tiny#45]
I just wanna let you know that the compilation of gettext-tiny from master fails on i586:

cc -o msgfmt src/msgfmt.o src/poparser.o src/StringEscape.o -s 
/tools/lib32/gcc/i586-linux-musl/9.1.1/../../../../i586-linux-musl/bin/ld: src/msgfmt.o: in function `process':
msgfmt.c:(.text+0x59b): undefined reference to `__stack_chk_fail_local'
/tools/lib32/gcc/i586-linux-musl/9.1.1/../../../../i586-linux-musl/bin/ld: src/msgfmt.o: in function `set_file':
msgfmt.c:(.text+0x6ba): undefined reference to `__stack_chk_fail_local'
/tools/lib32/gcc/i586-linux-musl/9.1.1/../../../../i586-linux-musl/bin/ld: src/msgfmt.o: in function `main':
msgfmt.c:(.text.startup+0x85b): undefined reference to `__stack_chk_fail_local'
/tools/lib32/gcc/i586-linux-musl/9.1.1/../../../../i586-linux-musl/bin/ld: src/poparser.o: in function `poparser_feed_line':
poparser.c:(.text+0x8e9): undefined reference to `__stack_chk_fail_local'
collect2: error: ld returned 1 exit status
make: *** [Makefile:70: msgfmt] Error 1

Note: I have PIE and SSP enabled by default in the compiler, but it works without any problems under x86_64.

**Comment by rofl0r** [comment]
this is a problem between musl and GCC on i486, not related to gettext-tiny. see https://github.com/sabotage-linux/sabotage/commit/0973b739276c756d341ca24a7aadc69670ed8bb8
