### ISSUE TITLE
failed to build gedit 3.34.1

### ISSUE THREAD

**Issue by protonesso** [sabotage-linux/gettext-tiny#47]
Hi, I'm building gedit version 3.34.1 with gettext-tiny. I'm using latest commit and I've got this:
```
FAILED: plugins/docinfo/docinfo.plugin 
/usr/bin/msgfmt --desktop --keyword=Name --keyword=Description --template=../plugins/docinfo/docinfo.plugin.desktop.in -d /usr/ports/packages/gedit/work/src/gedit-3.34.1/po --output=plugins/docinfo/docinfo.plugin
fopen: No such file or directory
```

**Comment by rofl0r** [comment]
so which file is missing?

**Comment by protonesso** [comment]
No idea. I will do verbose build today

**Comment by protonesso** [comment]
the build log: https://paste.ubuntu.com/p/7fqgX9Jykp/

**Comment by rofl0r** [comment]
and? that's basically what you posted already, but with more noise around it. which file isn't found? (use strace)

**Comment by protonesso** [comment]
I don't know. How to verbose msgfmt output?

2019年11月27日(水) 22:25 rofl0r <notifications@github.com>:

**Comment by rofl0r** [comment]
just cd to the right dir then run `strace -o log -f mgsfmt ...` with the command the build uses. then check log to find which file causes ENOENT to be returned.

**Comment by protonesso** [comment]
Okay. I will send info tomorrow. Thanks!

2019年11月27日(水) 23:18 rofl0r <notifications@github.com>:

**Comment by protonesso** [comment]
```
bash-5.0# strace -o log -f msgfmt --desktop --keyword=Name --keyword=Description --template=../plugins/docinfo/docinfo.plugin.desktop.in -d /usr/ports/packages/gedit/work/src/gedit-3.34.1/po --output=plugins/docinfo/docinfo.plugin
fopen: No such file or directory
```

**Comment by rofl0r** [comment]
> just cd to the right dir then run strace -o log -f mgsfmt ... with the command the build uses. then check log to find which file causes ENOENT to be returned.

there were two sentences in my response.

1) cd to the right dir then run strace -o log -f mgsfmt ... with the command the build uses
2) check log to find which file causes ENOENT to be returned.

**Comment by xhebox** [comment]
it's because that msgfmt does not handle command line opts correctly. should be closed by the commit. tested with gedit 3.34.0.

**Comment by protonesso** [comment]
@xhebox will test!
