### ISSUE TITLE
Autoreconf fails on path ending with the string "m4"

### ISSUE THREAD

**Issue by giuliobenetti** [sabotage-linux/gettext-tiny#48]
In Buildroot if we build some package enabling gettext-tiny instead of gettext on a path containing string "m4" autoreconf fails. I point you Buildroot bug:
https://bugs.busybox.net/show_bug.cgi?id=12481

I'm trying to figure out what the problem is and eventually open a PR, but advice/suggestion is welcome.

Thanks

**Comment by hthiery** [comment]
Could that be a place where this issue comes from?

https://github.com/sabotage-linux/gettext-tiny/blob/master/Makefile#L91

**Comment by hthiery** [comment]
`make prefix=test-m4 install` will show the issue

**Comment by giuliobenetti** [comment]
@hthiery thank you, yes that's the right point.
I've opened PR #49 for that. It should work fine. Hope it looks good.

**Comment by rofl0r** [comment]
let's leave this open until the issue is fixed in master

**Comment by giuliobenetti** [comment]
@rofl0r yes sorry, my bad.

**Comment by xhebox** [comment]
closed by https://github.com/sabotage-linux/gettext-tiny/pull/49.

feel free to reopen if there's any other problem.
