### ISSUE TITLE
Copyright violation: gettext.html is not under MIT license

### ISSUE THREAD

**Issue by bhaible** [sabotage-linux/gettext-tiny#52]
The gettext.html file, in Appendix C "Licenses", states that "This manual is free documentation. It is dually licensed under the GNU FDL and the GNU GPL."

It is therefore wrong to distribute it via github in a package whose LICENSE file is an MIT license.

Please change the LICENSE file, to clarify, or remove the gettext.html from the package.

You are of course welcome to point to the URL https://www.gnu.org/software/gettext/manual/ , where people can find the up-to-date documentation of GNU gettext.

**Comment by rofl0r** [comment]
is the manual linked against the binary ? if so it would indeed be a copyright violation.

**Comment by bhaible** [comment]
It is not linked against a binary. But copyright and licenses apply not only to code, but also to documentation. This documentation file is dually licensed under the GNU FDL and the GNU GPL; it is not allowed to distribute it in a way that makes people think that it is under MIT license.

**Comment by rofl0r** [comment]
the purpose of the doc/ dir is that i want the relevant docs at my fingertips, instead of having to surf around in the net first. it's not shipped with release tarballs.

anyway, would it, according to your view, be sufficient to add a paragraph like 

> files contained in the doc/ directory may be licensed under different terms, if so, it is noted there in the respective file.

?

**Comment by bhaible** [comment]
> the purpose of the doc/ dir is that i want the relevant docs at my fingertips, instead of having to surf around in the net first. it's not shipped with release tarballs.

Nevertheless, its presence in a public github repository counts as a "distribution": You are making it available to other people in the world.

> would it, according to your view, be sufficient to add a paragraph like ...

Yes, the proposed text would be perfect.

Thanks!
