### ISSUE TITLE
autopoint.in violates POSIX sh

### ISSUE THREAD

**Issue by mirabilos** [sabotage-linux/gettext-tiny#65]
Patch:

```
--- autopoint.in~	2024-01-20 22:53:28.014897848 +0100
+++ autopoint.in	2024-01-20 22:53:58.155007025 +0100
@@ -15,8 +15,8 @@ dirprefix=""
 while read line
 do
   if [ "${line##*AC_CONFIG_AUX_DIR}" != "$line" ]; then
-    dirprefix="${line##*([}"
-    dirprefix="${dirprefix%%])*}"
+    dirprefix="${line##*\([}"
+    dirprefix="${dirprefix%%]\)*}"
     mkdir -p "${dirprefix}"
   fi
   
```

Unfortunately, shellcheck does not yet flag this; I’ve filed [a feature request](https://github.com/koalaman/shellcheck/issues/2906) with them for it.

The root cause of the issue is that POSIX requires “the application” (the script / script writer) to escape special characters because “the implementation” (the shell) to add extensions to otherwise invalid cases. All Korn shells do this:

```
$ foo='abbbc'; echo "${foo##a*(b)}"
c
```

POSIX is derived from the Korn shell, so this is permitted.

Note that you could even do…

```
+    dirprefix=${line##*\([}
+    dirprefix=${dirprefix%%]\)*}
```

… as the outer doublequotes around a `${…}` expression used as RHS of a shell variable (POSIX: shell parameter) assignment are almost always redundant.

Another alternative spelling:

```
+    dirprefix=${line##*"(["}
+    dirprefix=${dirprefix%%"])"*}
```

**Comment by rofl0r** [comment]
care to make a PR ? you just have to click on edit on the file here in the repo and github forks it automatically for a PR.

**Comment by mirabilos** [comment]
rofl0r dixit:

>care to make a PR ? you just have to click on edit on the file here in

Nah, I can’t rightfully test things, and there’s probably more
than one file in the repo and you’d have to check if the others
would also be affected, etc… (I’m the mksh developer, I only
have been pointed at that one file by a user)

bye,
//mirabilos
-- 
„Cool, /usr/share/doc/mksh/examples/uhr.gz ist ja ein Grund,
mksh auf jedem System zu installieren.“
	-- XTaran auf der OpenRheinRuhr, ganz begeistert
(EN: “[…]uhr.gz is a reason to install mksh on every system.”)
